# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-532db2e8-dce5-4805-aa5d-eceed8cd85c9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-532db2e8-dce5-4805-aa5d-eceed8cd85c9".device = "/dev/disk/by-uuid/532db2e8-dce5-4805-aa5d-eceed8cd85c9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3BF8-6984";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-092d804b-6569-4774-a75b-17b6aa3cda8e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
